# Generated by Django 5.0.6 on 2025-01-31 12:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_en', models.TextField(null=True)),
                ('question_hi', models.TextField(null=True)),
                ('question_bn', models.TextField(null=True)),
                ('answer', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
