# Generated by Django 5.0.6 on 2025-01-31 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_bn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hi',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
